{application,toolshed,
             [{config_mtime,1746179085},
              {optional_applications,[inets,ssl,nerves_runtime]},
              {applications,[kernel,stdlib,elixir,iex,logger,inets,ssl,
                             nerves_runtime]},
              {description,"Use Toolshed for more IEx helpers"},
              {modules,['Elixir.Toolshed','Elixir.Toolshed.Impl',
                        'Elixir.Toolshed.OneBeam',
                        'Elixir.Toolshed.Top.Processes',
                        'Elixir.Toolshed.Top.Report',
                        'Elixir.Toolshed.Top.Server',
                        'Elixir.Toolshed.Watcher']},
              {registered,[]},
              {vsn,"0.4.1"},
              {env,[{speed_test_url,<<"http://dl.nerves-project.org/speed_test/10MB.bin">>}]}]}.
