{application,ring_logger,
             [{config_mtime,1746179084},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,circular_buffer]},
              {description,"A ring buffer backend for Elixir Logger with IO streaming"},
              {modules,['Elixir.RingLogger','Elixir.RingLogger.Autoclient',
                        'Elixir.RingLogger.Buffer','Elixir.RingLogger.Client',
                        'Elixir.RingLogger.Persistence',
                        'Elixir.RingLogger.Server',
                        'Elixir.RingLogger.Viewer']},
              {registered,[]},
              {vsn,"0.11.3"}]}.
